apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-example-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xdlc-labs/example-service.git
    targetRevision: develop
    path: deploy
    helm:
      valueFiles:
        - ../gitops/values/dev/example-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
